force-app/main/default/objects/CQ_SD_SQX_Manager__c/CQ_SD_SQX_Manager__c.object-meta.xml
<CustomObject>
    <description>This Object Contains the Record of Manages</description>
    <label>Manager</label>
    <nameField>
        <label>CQ SD SQX  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CQ_SD_SQX_Manager__c/fields/CQ_SD_Requirement_Status__c.field-meta.xml
<CustomField>
    <fullName>CQ_SD_Requirement_Status__c</fullName>
    <description>represent the Requirement Status of manager</description>
    <label>Requirement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application Received( Draft )</fullName>
                <default>true</default>
                <label>Application Received( Draft )</label>
            </value>
            <value>
                <fullName>Application In Progress</fullName>
            </value>
            <value>
                <fullName>Application Completed</fullName>
            </value>
            <value>
                <fullName>Application Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CQ_SD_Manager_Trigger_Handler.cls
public class CQ_SD_Manager_Trigger_Handler { 
    
	
    public static void beforeUpdate(List<CQ_SD_SQX_Manager__c> newManagers, Map<Id, CQ_SD_SQX_Manager__c> oldManagers) {
        for (CQ_SD_SQX_Manager__c newManager : newManagers) {
            CQ_SD_SQX_Manager__c oldManager = oldManagers.get(newManager.Id);

            if (oldManager.CQ_SD_Requirement_Status__c == 'Application Closed') {
                newManager.CQ_SD_Requirement_Status__c.addError('Updating the status to Closed is not allowed.');
            }
        }
    }
}