force-app/main/default/objects/Your_Investment__c/Your_Investment__c.object-meta.xml
<CustomObject>
    <label>Your Investment</label>
    <nameField>
        <label>Your Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Your Investments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Your_Investment__c/fields/Amount_Invested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invested__c</fullName>
    <label>Amount Invested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvestmentObjectController.cls
public without sharing class InvestmentObjectController {
    @AuraEnabled(cacheable=true)
    public static List<Your_Investment__c> getObjectDetails() {
        
        String adminProfileName = 'System Administrator'; // Replace with the actual name of your admin profile

		String adminProfileId = [SELECT Id FROM Profile WHERE Name = :adminProfileName LIMIT 1].Id;
        
        List<Your_Investment__c> InvestmentList = new List<Your_Investment__c>();
        
             if (UserInfo.getProfileId() == adminProfileId) {
    // If the user is an admin, retrieve data for all owners
	 InvestmentList = [SELECT ID, Name, Total_Quantity__c, Amount_Invested__c FROM Your_Investment__c];
                 
} else {        
	
		InvestmentList = [SELECT ID,Name,Total_Quantity__c,Amount_Invested__c FROM Your_Investment__c WHERE OwnerId = :UserInfo.getUserId()];
    
          
}
        
         return InvestmentList;
    }
    }