force-app/main/default/objects/Watchlist__c/Watchlist__c.object-meta.xml
<CustomObject>
    <label>Watchlist</label>
    <nameField>
        <label>Ticker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WatchLists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Watchlist__c/fields/Current_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Price__c</fullName>
    <label>Current Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Watchlist__c/fields/Stock_Available__c.field-meta.xml
<CustomField>
    <fullName>Stock_Available__c</fullName>
    <label>Stock Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WatchlistAPexClass.cls
public class WatchlistAPexClass {

    /**
     * Aura-enabled method to retrieve a list of Watchlist records.
     * 
     * @return List of Watchlist records or null if the list is empty.
     */
    @AuraEnabled
    public static List<Watchlist__c> getWatchlist() {
        // Query Watchlist records from the database
        List<Watchlist__c> watchlistList = [SELECT ID, Name, Current_Price__c, Stock_Available__c, Logo__c FROM Watchlist__c];

        // Check if the list is not empty
        if (!watchlistList.isEmpty()) {
            return watchlistList;
        }

        // Return null if the list is empty
        return null;
    }
}